# Generated by Django 5.1.3 on 2024-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_course_options_alter_topic_options_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
