# Generated by Django 5.1.3 on 2024-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0012_alter_assignmentsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link_work',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка на работу'),
        ),
    ]
