# Generated by Django 5.1.3 on 2024-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0013_customuser_link_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такое имя уже существует, выбирете другое'}, help_text='Введите имя пользователя', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
