# Generated by Django 5.1.3 on 2024-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0015_customuser_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='Неизвестно', max_length=50, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='Неизвестно', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_pay',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='index',
            field=models.CharField(blank=True, default='Неизвестно', max_length=50, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mid_name',
            field=models.CharField(blank=True, default='Неизвестно', max_length=100, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='Неизвестно', max_length=100, verbose_name='Телефон'),
        ),
    ]
