# Generated by Django 5.1.3 on 2024-12-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0016_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mid_name',
            field=models.CharField(blank=True, default='Неизвестно', max_length=100, verbose_name='Отчество'),
        ),
    ]
